version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"  # Exclude indirect dependencies
    groups:
      all-dependencies:
        patterns: ["*"]
